import Page from '../components/Page.jsx'
import { getPetsWithDevices, getReading, makeAdvice } from '../mock.js'
import { useEffect, useState } from 'react'

export default function Dashboard(){
  const [withDevs,setWithDevs]=useState(getPetsWithDevices())
  const [readings,setReadings]=useState({})
  useEffect(()=>{const id=setInterval(()=>{setWithDevs(getPetsWithDevices()); const next={}; getPetsWithDevices().forEach(p=>{const metrics=new Set(p.dispositivos.flatMap(d=>d.metricas)); next[p.id]={}; metrics.forEach(m=>{next[p.id][m]=getReading(m)})}); setReadings(next)},1500); return()=>clearInterval(id)},[])
  return(<Page title='Panel general'>{withDevs.length===0&&<p className='text-sm text-gray-500'>Vincula un dispositivo desde “Mis mascotas” para ver lecturas aquí.</p>}<div className='grid sm:grid-cols-2 lg:grid-cols-3 gap-4'>{withDevs.map(p=>(<div key={p.id} className='bg-white rounded-2xl shadow-soft p-4 border border-emerald-100'><div className='flex items-center justify-between'><div><p className='font-semibold text-emerald-800'>{p.nombre}</p><p className='text-xs text-gray-500'>{p.especie} {p.raza?`• ${p.raza}`:''} • {p.edad?.toFixed?.(1)} años • {p.fase}</p></div><div className='text-xs text-gray-400'>{p.dispositivos.length} dispositivo(s)</div></div><div className='mt-3 text-sm text-gray-700 space-y-1'>{p.dispositivos.flatMap(d=>d.metricas).includes('temp')&&<p>🌡️ Temp: {readings[p.id]?.temp?.toFixed?.(1)} °C</p>}{p.dispositivos.flatMap(d=>d.metricas).includes('hum')&&<p>💧 Humedad: {readings[p.id]?.hum?.toFixed?.(0)}%</p>}{p.dispositivos.flatMap(d=>d.metricas).includes('ph')&&<p>💧 pH: {readings[p.id]?.ph?.toFixed?.(2)}</p>}{p.dispositivos.flatMap(d=>d.metricas).includes('actividad')&&<p>🏃 Actividad: {readings[p.id]?.actividad?.toFixed?.(0)}%</p>}{p.dispositivos.flatMap(d=>d.metricas).includes('pulso')&&<p>❤️ Pulso: {readings[p.id]?.pulso?.toFixed?.(0)} bpm</p>}</div><div className='mt-3 text-sm text-emerald-700'>• {makeAdvice('hum',readings[p.id]?.hum??52,p.especie)}</div></div>))}</div></Page>) }
